import { type Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ClickSpark from "@/components/ClickSpark";
import TextCursor from "@/components/TextCursor";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TextCursor
          text="Hi_Chat"
          delay={0.01}
          spacing={120}
          followMouseDirection={true}
          randomFloat={true}
          exitDuration={0.01}
          removalInterval={20}
          maxPoints={2}
        />
        <ClickSpark
          sparkColor="#ffa500"
          sparkSize={10}
          sparkRadius={15}
          sparkCount={8}
          duration={400}
        >
          {children}
        </ClickSpark>
      </body>
    </html>
  );
}
